.TH "fmtutil\&.cnf" "5" "October 2000" "teTeX" "teTeX" 
.PP 
.SH "NAME" 
fmtutil\&.cnf \- configuration file for fmtutil
.PP 
.SH "DESCRIPTION" 
.PP 
The \fIfmtutil\&.cnf\fP file contains the configuration information
for \fBfmtutil\fP(8)\&.  Each line contains the name of the format
(e\&.g\&., ``tex\'\', ``latex\'\', ``omega\'\'), the name of the engine that
is used by that format (e\&.g\&., ``tex\'\', ``etex\'\', ``omega\'\'), the pattern
file (e\&.g\&., \fIlanguage\&.dat\fP, \fIlanguage\&.def\fP), and any
arguments (name of an \fI\&.ini\fP file)\&.  
.PP 
Fields are separated by whitespace\& and complete lines can be commented
out with ``#\'\'\&.  The ``pattern file\'\' field cannot be used to
define a file that is used while building the format\&.
It tells \fBfmtutil\fP which files (separated by commas) the
format creation procedure reads\& and it has an effect to the options
\fI--showhyphen\fP and \fI--byhyphen\fP\&.
If the format has no way to
customize hyphenation, a ``-\'\' can be used to indicate this\&.
.PP 
.SH "NOTES" 
.PP 
The \fBtex\fP(1) and \fBamstex\fP(1) formats always load
\fIhyphen\&.tex\fP\&.  No customization by a pattern file is available
for these formats\&. Therefore, the pattern-file field for the
\fBtex\fP and \fBamstex\fP is usually indicated to be empty (``-\'\')\&.
.PP 
You can, however, build customized formats on top of plain
\fBtex\fP(1) or \fBamstex\fP(1) by using \fIbplain\&.tex\fP instead of
\fIplain\&.tex\fP (b for the \fIBabel\fP system). See, for example,
the \fIbplain\&.ini\fP file for the bplain format)\&.
.PP 
\fBetex\fP(1) loads \fIlanguage\&.def\fP, not
\fIlanguage\&.dat\fP\&.
.PP 
Symbolic links to the correct engines (e\&.g\&., bplain -> tex)
are generated by the \fBtexlinks\fP(8) script\&.   Remember to run
\fBtexlinks\fP(8) if you run \fBfmtutil\fP(8) yourself, rather
than using the FORMATS option in \fBtexconfig\fP(8)\&.
.PP 
.SH "FILES" 
.PP 
.IP "\fIfmtutil\&.cnf\fP" 
default configuration file
.IP "\fIlanguage\&.dat\fP" 
hyphenation pattern file
.IP "\fIlanguage\&.def\fP" 
hyphenation pattern file
.IP "\fIlanguage\&.dat.lua\fP" 
hyphenation pattern file
.PP 
.SH "SEE ALSO" 
.PP 
\fBamstex\fP(1), \fBetex\fP(1), \fBfmtutil\fP(8),
\fBtex\fP(1), \fBtexconfig\fP(8), \fBtexlinks\fP(8)\&.
.PP 
Web page: <http://tug\&.org/teTeX/>
.PP 
.SH "BUGS" 
.PP 
None known, but report any bugs found to <tetex@dbs\&.uni-hannover\&.de> (mailing list)\&.
.PP 
.SH "AUTHOR" 
.PP 
\fIfmtutil\&.cnf\fP was written by Thomas Esser 
<te@dbs\&.uni-hannover\&.de>, and is Copyright 1998,
1999 but released into the public domain\&.
.PP 
This manual page was written by C\&.M\&. Connelly
<c@eskimo\&.com>, for
the Debian GNU/Linux system\&.  It may be used by other distributions
without contacting the author\&.  Any mistakes or omissions in the
manual page are my fault; inquiries about or corrections to this
manual page should be directed to me (and not to the primary author)\&.
