touch Resources_mini/bin/awk
touch Resources_mini/bin/bc
touch Resources_mini/bin/cat
touch Resources_mini/bin/cd
touch Resources_mini/bin/chflags
touch Resources_mini/bin/cksum
touch Resources_mini/bin/chmod
touch Resources_mini/bin/compress
touch Resources_mini/bin/cp
touch Resources_mini/bin/curl
touch Resources_mini/bin/date
touch Resources_mini/bin/dc
touch Resources_mini/bin/diff
touch Resources_mini/bin/dig
touch Resources_mini/bin/du
touch Resources_mini/bin/echo
touch Resources_mini/bin/ed
touch Resources_mini/bin/egrep
touch Resources_mini/bin/env
touch Resources_mini/bin/fgrep
touch Resources_mini/bin/find
touch Resources_mini/bin/grep
touch Resources_mini/bin/gunzip
touch Resources_mini/bin/gzip
touch Resources_mini/bin/head
touch Resources_mini/bin/host
touch Resources_mini/bin/ifconfig
touch Resources_mini/bin/jsc
touch Resources_mini/bin/link
touch Resources_mini/bin/ln
touch Resources_mini/bin/ls
touch Resources_mini/bin/lua
touch Resources_mini/bin/luac
touch Resources_mini/bin/md5
touch Resources_mini/bin/mkdir
touch Resources_mini/bin/mv
touch Resources_mini/bin/nc
touch Resources_mini/bin/nslookup
touch Resources_mini/bin/openurl
touch Resources_mini/bin/open
touch Resources_mini/bin/pbcopy
touch Resources_mini/bin/pbpaste
touch Resources_mini/bin/ping
touch Resources_mini/bin/printenv
touch Resources_mini/bin/pwd
touch Resources_mini/bin/python3
touch Resources_mini/bin/python
touch Resources_mini/bin/pythonA
touch Resources_mini/bin/readlink
touch Resources_mini/bin/rlogin
touch Resources_mini/bin/rm
touch Resources_mini/bin/rmdir
touch Resources_mini/bin/say
touch Resources_mini/bin/scp
touch Resources_mini/bin/sed
touch Resources_mini/bin/setenv
touch Resources_mini/bin/sftp
touch Resources_mini/bin/sh
touch Resources_mini/bin/ssh
touch Resources_mini/bin/ssh-keygen
touch Resources_mini/bin/sort
touch Resources_mini/bin/stat
touch Resources_mini/bin/sum
touch Resources_mini/bin/tail
touch Resources_mini/bin/tar
touch Resources_mini/bin/tee
touch Resources_mini/bin/telnet
touch Resources_mini/bin/touch
touch Resources_mini/bin/tr
touch Resources_mini/bin/uname
touch Resources_mini/bin/uncompress
touch Resources_mini/bin/uniq
touch Resources_mini/bin/unlink
touch Resources_mini/bin/unsetenv
touch Resources_mini/bin/uptime
touch Resources_mini/bin/vim
touch Resources_mini/bin/wc
touch Resources_mini/bin/whoami
touch Resources_mini/bin/whois
touch Resources_mini/bin/xargs
touch Resources_mini/bin/task
touch Resources_mini/bin/lex
touch Resources_mini/bin/calc
touch Resources_mini/bin/less
touch Resources_mini/bin/more
touch Resources_mini/bin/lessecho
touch Resources_mini/bin/mandoc
touch Resources_mini/bin/mandocdb
touch Resources_mini/bin/man
touch Resources_mini/bin/apropos
touch Resources_mini/bin/whatis
touch Resources_mini/bin/wol
touch Resources_mini/bin/compare
touch Resources_mini/bin/composite
touch Resources_mini/bin/conjure
touch Resources_mini/bin/convert
touch Resources_mini/bin/identify
touch Resources_mini/bin/import
touch Resources_mini/bin/magick-script
touch Resources_mini/bin/mogrify
touch Resources_mini/bin/montage
touch Resources_mini/bin/stream

