touch Resources/bin/awk
touch Resources/bin/bc
touch Resources/bin/cat
touch Resources/bin/cd
touch Resources/bin/chflags
touch Resources/bin/cksum
touch Resources/bin/chmod
touch Resources/bin/compress
touch Resources/bin/cp
touch Resources/bin/curl
touch Resources/bin/date
touch Resources/bin/dc
touch Resources/bin/diff
touch Resources/bin/dig
touch Resources/bin/du
touch Resources/bin/echo
touch Resources/bin/ed
touch Resources/bin/egrep
touch Resources/bin/env
touch Resources/bin/fgrep
touch Resources/bin/find
touch Resources/bin/grep
touch Resources/bin/gunzip
touch Resources/bin/gzip
touch Resources/bin/head
touch Resources/bin/host
touch Resources/bin/ifconfig
touch Resources/bin/jsc
touch Resources/bin/link
touch Resources/bin/ln
touch Resources/bin/ls
touch Resources/bin/lua
touch Resources/bin/luac
touch Resources/bin/md5
touch Resources/bin/mkdir
touch Resources/bin/mv
touch Resources/bin/nc
touch Resources/bin/nslookup
touch Resources/bin/openurl
touch Resources/bin/open
touch Resources/bin/pbcopy
touch Resources/bin/pbpaste
touch Resources/bin/ping
touch Resources/bin/printenv
touch Resources/bin/pwd
touch Resources/bin/python3
touch Resources/bin/python
touch Resources/bin/pythonA
touch Resources/bin/readlink
touch Resources/bin/rlogin
touch Resources/bin/rm
touch Resources/bin/rmdir
touch Resources/bin/say
touch Resources/bin/scp
touch Resources/bin/sed
touch Resources/bin/setenv
touch Resources/bin/sftp
touch Resources/bin/sh
touch Resources/bin/ssh
touch Resources/bin/ssh-keygen
touch Resources/bin/sort
touch Resources/bin/stat
touch Resources/bin/sum
touch Resources/bin/tail
touch Resources/bin/tar
touch Resources/bin/tee
touch Resources/bin/telnet
touch Resources/bin/touch
touch Resources/bin/tr
touch Resources/bin/uname
touch Resources/bin/uncompress
touch Resources/bin/uniq
touch Resources/bin/unlink
touch Resources/bin/unsetenv
touch Resources/bin/uptime
touch Resources/bin/vim
touch Resources/bin/wc
touch Resources/bin/whoami
touch Resources/bin/whois
touch Resources/bin/xargs
touch Resources/bin/llvm-dis
touch Resources/bin/opt
touch Resources/bin/llvm-link
touch Resources/bin/lli
touch Resources/bin/llc
touch Resources/bin/lld
touch Resources/bin/ld
touch Resources/bin/ar
touch Resources/bin/ranlib
touch Resources/bin/wasm-ld
touch Resources/bin/lld-link
touch Resources/bin/ld.lld
touch Resources/bin/ld64.lld
touch Resources/bin/clang
touch Resources/bin/clang++
touch Resources/bin/task
touch Resources/bin/lex
touch Resources/bin/calc
touch Resources/bin/less
touch Resources/bin/more
touch Resources/bin/lessecho
touch Resources/bin/mandoc
touch Resources/bin/mandocdb
touch Resources/bin/man
touch Resources/bin/apropos
touch Resources/bin/whatis
touch Resources/bin/wol
touch Resources/bin/compare
touch Resources/bin/composite
touch Resources/bin/conjure
touch Resources/bin/convert
touch Resources/bin/identify
touch Resources/bin/import
touch Resources/bin/magick-script
touch Resources/bin/mogrify
touch Resources/bin/montage
touch Resources/bin/stream
touch Resources/bin/amstex
touch Resources/bin/bibtex
touch Resources/bin/cslatex
touch Resources/bin/csplain
touch Resources/bin/eplain
touch Resources/bin/etex
touch Resources/bin/jadetex
touch Resources/bin/latex
touch Resources/bin/mex
touch Resources/bin/mllatex
touch Resources/bin/mltex
touch Resources/bin/pdfcslatex
touch Resources/bin/pdfcsplain
touch Resources/bin/pdfetex
touch Resources/bin/pdfjadetex
touch Resources/bin/pdflatex
touch Resources/bin/pdfmex
touch Resources/bin/pdftex
touch Resources/bin/pdfxmltex
touch Resources/bin/tex
touch Resources/bin/texsis
touch Resources/bin/utf8mex
touch Resources/bin/xmltex
touch Resources/bin/dvilualatex
touch Resources/bin/dviluatex
touch Resources/bin/lualatex
touch Resources/bin/luatex
touch Resources/bin/texlua
touch Resources/bin/texluac

