.TH "fontinst" "1" "May 2000" "teTeX" "teTeX" 
.PP 
.SH "NAME" 
fontinst \- utility to run TeX as fontinst 
.PP 
.SH "SYNOPSIS" 
.PP 
\fBfontinst\fP \fIpackage\fP
.PP 
.SH "DESCRIPTION" 
.PP 
\fBfontinst\fP runs \fBtex\fP(1) with the \fB--progname\fP flag set to
pretend to be the program fontinst (affecting Karl Berry paths)\&.
.PP 
Typing
.PP 
\f(CWfontinst fontinst\&.sty\fP
.PP 
will start \fBtex\fP(1) and give the user an interactive prompt
(\f(CW*\fP) where fontinst commands can be typed (such as
\f(CW\elatinfamily{ptm}{}\ebye\fP)\&.
.PP 
.SH "SEE ALSO" 
.PP 
\fBtex\fP(1)
.PP 
The fontinst manual, \fIfontinst\&.tex\fP\&.
.PP 
Web page: <http://tug\&.org/applications/fontinst/>
.PP 
.SH "BUGS" 
.PP 
None known, but report any bugs found to tex-fonts@tug\&.org (mailing list)\&.
.PP 
.SH "AUTHOR" 
.PP 
Thomas Esser 
<te@dbs\&.uni-hannover\&.de>
.PP 
This manual page was written by C\&.M\&. Connelly
<c@eskimo\&.com>, for
the Debian GNU/Linux system\&.  It may be used by other distributions
without contacting the author\&.  Any mistakes or omissions in the
manual page are my fault; inquiries about or corrections to this
manual page should be directed to me (and not to the primary author)\&.
