.TH INCLUDERES 1 "PSUtils"
.SH NAME
includeres \- filter to include resources in a PostScript document
.SH SYNOPSIS
.B includeres 
.RI < document.ps
.RI > output.ps
.SH DESCRIPTION
.B Includeres
includes resources (fonts, procsets, patterns, files, etc.) in place of
.B %%IncludeResource
comments in a PostScript document. The resources are searched for
under the resource name, and with an appropriate extension.
The pipeline
.sp
.ce
extractres file.ps | includeres >out.ps
.sp
will move all resources appearing in a document to the document prologue,
removing redundant copies. The output file can then be put through page
re-arrangement filters such as
.B psnup
or 
.B pstops
safely.
.SH AUTHOR
Written by Angus J. C. Duggan.
.SH "SEE ALSO"
.BR psutils (1)
.SH TRADEMARKS
.B PostScript
is a trademark of Adobe Systems Incorporated.
.SH BUGS
.B includeres
does not alter the
.B %%DocumentNeededResources
comments.
