.TH PSJOIN "1" "November 2003" "psjoin 0.3" "User Commands"
.SH NAME
psjoin \- psjoin
.SH SYNOPSIS
.B psjoin
.RI [ option ...]
.IR filename ...
.SH DESCRIPTION
.B psjoin
\- concatenate PostScript files (version 0.3)
by Tom Sato <VEF00200@nifty.ne.jp>, http://member.nifty.ne.jp/tsato/
.SS "Option:"
.HP
\fB\-a\fR: align first page of each documents to odd page
.HP
\fB\-s\fR: try to close unclosed save operators
.HP
\fB\-p\fR: not strip prolog/trailer of the input files
.HP
\fB\-h\fR: display help
